name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@master
    - name: Install MONA
      run: sudo apt-get install mona
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:  pip install tox
    - name: Unit tests and coverage
      run: |
        tox -e py${{ matrix.python-version }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Generate Documentation
      run: tox -e docs